name: E2E test

on: [pull_request]

jobs:
  e2e_test:
    name: Run e2e test
    strategy:
      matrix:
        runs_on:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: cmd
    runs-on: ${{ matrix.runs_on.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Set up venv (windows)
        if: matrix.runs_on.os == 'windows-latest'
        run: |
          python -m venv venv
          . venv\Scripts\activate
          echo PATH=$PATH >> $GITHUB_ENV

      - name: Set up venv (linux & mac)
        if: matrix.runs_on.os != 'windows-latest'
        run: |
          python -m venv venv
          . venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      
      - name: Build RPC server
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          pip install -e .
          cd playpen
          pyinstaller build.spec

      
      
      
      
          

        